version: "3.8"

services:
  app:
    container_name: FastAPI
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_ENV: development
    
